### ISSUE TITLE
Fails to work with Gnome 3.16

### ISSUE THREAD

**Issue by GeraldPfeifer** [dnohales/battery-percentage-extension#1]
After this worked nicely with both Gnome 3.12 and 3.14, when I updated to Gnome 3.16
on openSUSE Factory/Tumbleweed today, this extension stopped working.

A quick hack to
.local/share/gnome-shell/extensions/battery-percentage@nohales.org/metadata.json
made this work again.

**Comment by dnohales** [comment]
Done, thanks for the reminder!

**Comment by GeraldPfeifer** [comment]
Cool, thank you for the quick fix!
